# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Otpdata',
        ),
        migrations.RenameModel(
            old_name='Todo',
            new_name='Tododata',
        ),
        migrations.RenameModel(
            old_name='Logins',
            new_name='Userdata',
        ),
    ]
