# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-26 04:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_remove_tododata_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododata',
            name='complete_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
